language: python

addons:
  apt:
    packages:
      - python-logilab-common

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov

# command to run tests
script:
  - pip install pytest
  - pytest radioencode/tests.py
  - coverage run radioencode/tests.py

after_success:
  - codecov
