language: python

addons:
  apt:
    packages:
      - python-logilab-common

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov

# command to run tests
script:
  - pip install pytest
  - pytest radioencode/__init__.py
  - coverage run radioencode/__init__.py

after_success:
  - codecov
  - pip install flake8
  - flake8 --count radioencode
